# Generated by Django 5.2.17 on 2026-10-05 18:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)], verbose_name='Número')),
                ('status', models.CharField(choices=[('DIS', 'Disponível'), ('RES', 'Reservado'), ('EMP', 'Emprestado'), ('MAN', 'Manutenção')], db_index=True, default='DIS', max_length=3)),
            ],
            options={
                'verbose_name': 'Equipamento (Notebook)',
                'verbose_name_plural': 'Equipamentos (Notebooks)',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail educacional')),
                ('turno', models.CharField(blank=True, choices=[('MAT', 'Matutino'), ('VES', 'Vespertino'), ('NOT', 'Noturno')], max_length=3)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, verbose_name='Data da reserva')),
                ('turno', models.CharField(choices=[('MAT', 'Matutino'), ('VES', 'Vespertino'), ('NOT', 'Noturno')], max_length=3, verbose_name='Turno da reserva')),
                ('quantidade', models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade solicitada (total do lote)')),
                ('lote', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('APR', 'Reservada'), ('ATI', 'Entregue'), ('CON', 'Concluída'), ('CAN', 'Cancelada')], db_index=True, default='PEN', max_length=3)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de entrega')),
                ('devolvida_em', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de devolução')),
                ('entregue_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.equipamento')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', 'turno', '-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da turma')),
                ('turno', models.CharField(choices=[('MAT', 'Matutino'), ('VES', 'Vespertino'), ('NOT', 'Noturno')], max_length=3)),
                ('instrutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_lecionadas', to=settings.AUTH_USER_MODEL, verbose_name='Instrutor responsável')),
            ],
            options={
                'ordering': ['turno', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='core.turma'),
        ),
    ]
