# Generated by Django 5.2.17 on 2026-10-05 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebooks_resgatados', to=settings.AUTH_USER_MODEL, verbose_name='Aluno que resgatou'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='core.turma'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Instrutor (quem reservou)'),
        ),
    ]
